### ISSUE TITLE
`no_alloc` feature is not additive

### ISSUE THREAD

**Issue by lnicola** [LeopoldArkham/humansize#29]
Rust features are supposed to be additive, but `no_alloc` isn't. It should probably be called `alloc`, or similar.

**Comment by LeopoldArkham** [comment]
You're right, but one of the main goals of the crate is that simple things should stay simple; since users needing a non-allocating formatter are probably a minority, I made it allocating by default with a subtractive feature flag because I wasn't aware of the existence of default features at the time.

It would have been the better choice but would now be a breaking change and I don't want to publish a major version for what's ultimately a (useful) convention.

If I ever publish a new major version, this will be fixed in it.
